Pin CloudNativePG to 0.21.6
Skip buggy versions 0.22.x and 0.26.x which have
duplicate grafana_dashboard key causing YAML parsing errors.

Using last known stable version 0.21.6.

Error: yaml: unmarshal errors: line 9: mapping key
'grafana_dashboard' already defined at line 8